### ISSUE TITLE
which is the default file to launch?

### ISSUE THREAD

**Issue by tnsankaran** [XeroAPI/xero-php-oauth2-starter#1]
I am trynig to logon Xero through authorization.php, I got only something went wrong screen in Xero. 
![image](https://user-images.githubusercontent.com/60739853/73935314-41281a00-4906-11ea-8d9a-8ac18208a358.png)

Also, I didnot see any link by default to Login to Xero as you have provided in description.

Any thing to correct in the settings?

**Comment by SidneyAllen** [comment]
@tnsankaran 

Thanks for the feedback - I've added an index.php in the root of the project as an entry point with a nice "Connect to Xero" button .  Download the latest, configure and see how you get along.

Cheers
