### ISSUE TITLE
[401] Client error: `PUT https://api.xero.com/api.xro/2.0/Contacts?summarizeErrors=true` resulted in a `401 Unauthorized` response: 

### ISSUE THREAD

**Issue by kunallibra** [XeroAPI/xero-php-oauth2-starter#13]
I am trying to create a new contact using Xero oAuth 2.0 and getting this error:

    [401] Client error: `PUT https://api.xero.com/api.xro/2.0/Contacts?summarizeErrors=true` resulted in a `401 Unauthorized` response: 

I have got my scopes as:

    'scopes'   => [
                'openid',
                'email',
                'profile',
                'offline_access',
                'accounting.settings',
                'accounting.contacts',
                'accounting.reports.read',
            ],

I am able to connect to Xero ([using this code][1]) and I get message **The App is connected to Xero** but when I use the following code:-
   

    public function xeroTest(OauthCredentialManager $xeroCredentials) {
    
            $apiInstance  = resolve(\XeroAPI\XeroPHP\Api\AccountingApi::class);
            $contact = resolve( \XeroAPI\XeroPHP\Models\Accounting\Contact::class);
            $contact->setName('Abcdef');
            $contact->setContactId('6d42f03b-181f-43e3-93fb-2025c0hjhe92');
    
            $apiResponse = $apiInstance->createContacts($xeroCredentials->getTenantId() ,$contact,true);
            $message = 'New Contact Name: ' . $apiResponse->getContacts()[0]->getName();
    
            return $message;
        }

Error:
    [401] Client error: `PUT https://api.xero.com/api.xro/2.0/Contacts?summarizeErrors=true` resulted in a `401 Unauthorized` response: 

  [1]: https://github.com/webfox/laravel-xero-oauth2#using-the-package

**Comment by MattR-Api** [comment]
Hi @kunallibra 

Thanks for getting in touch. 

Could you please email the API support team at api@xero.com with your Client ID so we can have a look at the Authorisation calls being made for your app? That way we don't have to share your private app details in a public place. 

Typically however, if you're receiving an 401 Error when calling an Endpoint, the required Scope for the Endpoint you're calling has not been included. For example, accounting.contacts is required to access the Contacts Endpoint. 

If the 401 is instead happening at the Authorisation Stage, where you're swapping the Authentication Code for your Access and Refresh Tokens, that means either the code being handed in is invalid, has timed out (the code times out after 5 min) or if you have multiple active apps, the code is meant for a different app.

Cheers 

Matt
