### ISSUE TITLE
Can you add a check for session_start()

### ISSUE THREAD

**Issue by monkey-code-good** [XeroAPI/xero-php-oauth2-starter#15]
https://github.com/XeroAPI/xero-php-oauth2-starter/blob/1352c186c2e2e1b2dae6422e11a2abf1f854b4db/authorization.php#L10

```php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
```
This definitely should work in PHP 5.6.

**Comment by monkey-code-good** [comment]
Oh, it's the storage constructor checking for the session and then running session_start and then this line 10 session_start() trying again. This session start should be at the top of the file. You should just remove the session_start() L10 and comment the class session_start(). IMHO ...

**Comment by SidneyAllen** [comment]
@monkey-code-good - thanks for the feedback - do you have time make a PR to fix this?

**Comment by monkey-code-good** [comment]
I'll sort sometime next week.

**Comment by monkey-code-good** [comment]
> I'll sort sometime next week.

or you can fix it that way 👍
