### ISSUE TITLE
The requested resource was not found on this server. [404]

### ISSUE THREAD

**Issue by SharkSkeleton** [XeroAPI/xero-php-oauth2-starter#17]
I am downloaded this project and try to use it, but have troubles after authorization. I choose Demo project (or any other) and have this message "The requested resource was not found on this server." But I am doing all step by step as in video tutorial (https://www.youtube.com/watch?v=vc1d7vdWeOE&t=404s). Please help me to fix this trouble..

**Comment by SidneyAllen** [comment]
Hi @SharkSkeleton - Did you modify the starter code at all?

The message you shared "The requested resource was not found on this server" is typically returned when you pass an invalid ID.  If you are preforming a GET to retrieve a specific object, you'll need a valid ID.

**Comment by SharkSkeleton** [comment]
Hi @SidneyAllen - First of all thank you for this stater project and answer.

Yes, I did modify project like in YouTube video, inserting my valid data, but have this trouble, and I can not handle it.
I have tried to create another project and connect to it, but it also return me this message.
Also I have tried to connect starter project on Node and it working without troubles

**Comment by SidneyAllen** [comment]
@SharkSkeleton - maybe you want to post the code you added to the php starter project so I can see it.

**Comment by monkey-code-good** [comment]
@SharkSkeleton Have you registered your app on https://developer.xero.com, copied the client ID, created and copied the secret ID and redirect URI to the provider config?

**Comment by SidneyAllen** [comment]
@SharkSkeleton - we didn't hear back from you around this issue, so I'll be closing it.

If you still have a problem, please create a new issue or comment on this thread

**Comment by mmbodirendani** [comment]
Hi @SidneyAllen  I am having the same problem with @SharkSkeleton,
I followed every step on that video but I am struggling to get to AuthorizesResorce.php.

I have sent you my code on your email sid.maestre@xero.com , code that I downloaded on github and modified the clientId and cliendSecret.

Please get back to me.
