### ISSUE TITLE
The requested resource was not found on this server. [404] #17

### ISSUE THREAD

**Issue by mmbodirendani** [XeroAPI/xero-php-oauth2-starter#19]
Hi @SidneyAllen I am having the same problem with @SharkSkeleton,
I followed every step on that video but I am struggling to get to AuthorizesResorce.php.

I have sent you my code on your email sid.maestre@xero.com , code that I downloaded on github and modified the clientId and cliendSecret.

Please get back to me.

**Comment by mmbodirendani** [comment]
Hi @SidneyAllen I am having the same problem with @SharkSkeleton,
I followed every step on that video but I am struggling to get to AuthorizesResorce.php.

I have sent you my code on your email sid.maestre@xero.com , code that I downloaded on github and modified the clientId and cliendSecret.

Please get back to me.

**Comment by SidneyAllen** [comment]
sounds like we got past the 404 on the callback url - closing this issue
