### ISSUE TITLE
having an error after gave authorisation 

### ISSUE THREAD

**Issue by mmbodirendani** [XeroAPI/xero-php-oauth2-starter#20]
Hi @SidneyAllen I am having the same problem with @SharkSkeleton,
I followed every step on that video but I am struggling to get to AuthorizesResorce.php.

I have sent you my code on your email sid.maestre@xero.com , code that I downloaded on github and modified the clientId and cliendSecret.

Please get back to me.

**Comment by SidneyAllen** [comment]
@mmbodirendani - you shared a screenshot of the callback.php page not being reached.

The default redirect URI for this project is http://localhost:8888/xero-php-oauth2-starter/callback.php

But if your local server has a different port number (not 8888) OR if you downloaded the project into a different folder structure the above path would be invalid.

I recommend looking at the full URL when you load the file index.php and see the "Connect to Xero" button to see if it varies from the redirect URI defined in the code AND on developer.xero.com in your Xero app.

![Screen Shot 2021-05-04 at 8 04 26 AM](https://user-images.githubusercontent.com/595967/117037854-d2c63900-acbb-11eb-8e61-ad13ae095d18.png)

**Comment by mmbodirendani** [comment]
Thank you for your response.

I managed to get it working,

Now I am struggling to pull the invoice number and Invoice amount.

Can you please assist me with a piece of code to pull invoice number and
invoice amount.

Kind regards.

**Comment by SidneyAllen** [comment]
@mmbodirendani - We have runnable code snippets that might help.

You can pass in an array of invoice numbers into the "getInvoices" method
https://xeroapi.github.io/xero-php-oauth2/docs/v2/accounting/index.html#api-Accounting-getInvoices

For the amount, you'll need to use the where clause

    $where="AmountDue>300.0";
       
    try {
            $result = $apiInstance->getInvoices($xeroTenantId, null, $where);
            $message=$result->count();
    } catch (Exception $e) {
        echo 'Exception when calling AccountingApi->getInvoices: ', $e->getMessage(), PHP_EOL;
    }
