### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\build_query() after authorising app

### ISSUE THREAD

**Issue by ryguy2407** [XeroAPI/xero-php-oauth2-starter#23]
I have the starter app running and all composer dependencies installed. I am trying to run this on a Laravel homestead instance.

When I click "connect to xero" button and I authorise the organisation I want to use I get the following error on callback.php

"Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query() in /home/vagrant/static/xero/vendor/xeroapi/xero-php-oauth2/lib/Api/IdentityApi.php on line 495"

I have tried deleting my vendor folder and composer.lock files and re running composer but I still get the same error?

Thanks :)

**Comment by SerKnight** [comment]
There’s a guzzle downgrade fix if you look through recently closed issues in the main project. 

The issue should be fixed in a future release but it’s a guzzle dependency thing

**Comment by ryguy2407** [comment]
Thank you, sorry I will look through that now.

**Comment by SerKnight** [comment]
Not at all! Write back if that doesn’t get you sorted.

**Comment by juuce** [comment]
> There’s a guzzle downgrade fix if you look through recently closed issues in the main project. The issue should be fixed in a future release but it’s a guzzle dependency thing
> […](#)
> On Aug 10, 2021, at 9:03 PM, Ryan Murray ***@***.***> wrote: ﻿ I have the starter app running and all composer dependencies installed. I am trying to run this on a Laravel homestead instance. When I click "connect to xero" button and I authorise the organisation I want to use I get the following error on callback.php "Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()" I have tried deleting my vendor folder and composer.lock files and re running composer but I still get the same error? Thanks :) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hi, Apologise for raising this again but I've got the same issue 'undefined function 'GuzzleHttp\Psr7\build_query()'
I've tried to look in the solved issues in 

- https://github.com/guzzle/guzzle/issues
- https://github.com/guzzle/psr7/issues

with limited success. Looking around it seems that Guzzle 7.3 somehow resolves this for a similar call type (https://github.com/guzzle/guzzle/issues/2824).
So, now I'm confused as what to do to resolve this within the library as it seems that it is up to 7.3.
I'm running php7.4.4 on apache (win)

Any someone has found a workaround?
Cheers,

UPDATE: Found a bit more info
https://github.com/guzzle/psr7#upgrading-from-function-api
Looking at /vendor/xeroapi/xero-php-oauth2/lib/Api/IdentityApi.php (lines (254 and 270) both use the function call.

I will try run some tests to replace these methods with the recommend upgrade from the table. Maybe a PR? Not too sure as I haven't done a PR in ages.

UPDATE:
Sorry - I see the PR now in the 'main' library (https://github.com/XeroAPI/xero-php-oauth2/pull/249)

Apologise for constant messaging but will leave my steps here just in case some else lands here.

**Comment by RettBehrens** [comment]
Resolved in the latest [release](https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.11.0). Made the necessary changes upstream in our code generator repo.

**Comment by jjshaw** [comment]
I have a similar issue except with 'GuzzleHttp\Psr7\Query' in callback.php after authorising...

"Fatal error: Uncaught Error: Class 'GuzzleHttp\Psr7\Query' not found in /var/www/vhosts/newhomesforsale.co.uk/vendor/xeroapi/xero-php-oauth2/lib/Api/IdentityApi.php:495 Stack trace: #0 /var/www/vhosts/newhomesforsale.co.uk/vendor/xeroapi/xero-php-oauth2/lib/Api/IdentityApi.php(302): XeroAPI\XeroPHP\Api\IdentityApi->getConnectionsRequest() #1 /var/www/vhosts/newhomesforsale.co.uk/vendor/xeroapi/xero-php-oauth2/lib/Api/IdentityApi.php(289): XeroAPI\XeroPHP\Api\IdentityApi->getConnectionsWithHttpInfo() #2 /var/www/vhosts/newhomesforsale.co.uk/dev.newhomesforsale.co.uk/xero/callback.php(42): XeroAPI\XeroPHP\Api\IdentityApi->getConnections() #3 {main} thrown in /var/www/vhosts/newhomesforsale.co.uk/vendor/xeroapi/xero-php-oauth2/lib/Api/IdentityApi.php on line 495"

UPDATE:
Solved dependancy conflict by upgrading to composer 2 and reupdating.
