### ISSUE TITLE
Issue with Guzzler

### ISSUE THREAD

**Issue by tydigital** [XeroAPI/xero-php-oauth2-starter#7]
Hi All,

Having an issue with the API when trying for the first time. This is with a clean LAMP install with SSL certificate in place.

When I go to authorization.php it takes me to Xero to authenticate and then back to callback.php with the following error.

`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/DOMAIN.CO.UK/public_html/xero/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200 Stack trace: #0 /var/www/DOMAIN.CO.UK/public_html/xero/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /var/www/DOMAIN.CO.UK/public_html/xero/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError() #2 /var/www/DOMAIN.CO.UK/public_html/xero/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish() #3 /var/www/DOMAIN.CO.UK/public_html/xero/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /var/www/DOMAIN.CO.UK/public_html/xero/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #5 /var/www/train in /var/www/DOMAIN.CO.UK/public_html/xero/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200`

Ive no idea what this issue is and ive tried looking online everywhere with no joy,

My set up is:
Centos 8
PHP 7.4.6
Apache2

**Comment by SidneyAllen** [comment]
@tydigital - just saw this issue.  I'm sorry but I don't have any idea 

Firebase has a similar issue - but no resolution
https://github.com/kreait/firebase-php/issues/346

Did you ever resolve this issue?
